title = "Will Craft Software"
baseURL = "https://willcraft.software/"
languageCode = "en-US"

theme = "detox"

[params]
    description = "Not only working software, but also well-crafted software."
    author = "We Will Craft"
    email = "we@willcraft.software"
    github = "wewillcraft"
